drop table events;
drop table statuses;
drop table event_types;
drop table appetizers;
drop table meats;
drop table desserts;
drop table soups;
drop table fishes;


CREATE TABLE IF NOT EXISTS statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    option VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS event_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    option VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS appetizers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    details VARCHAR(255) NOT NULL,
    photo VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS soups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    details VARCHAR(255) NOT NULL,
    photo VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS fishes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    details VARCHAR(255) NOT NULL,
    photo VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS meats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    details VARCHAR(255) NOT NULL,
    photo VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS desserts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    details VARCHAR(255) NOT NULL,
    photo VARCHAR(255)
);



CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    num_person SMALLINT NOT NULL,
    num_children SMALLINT NOT NULL,
    num_free_children SMALLINT NOT NULL,
    event_date_start TIMESTAMP ,
    event_date_end TIMESTAMP ,
    event_type BIGINT NOT NULL REFERENCES event_types(id),
    appetizer BIGINT NOT NULL REFERENCES appetizers(id),
    soup BIGINT NOT NULL REFERENCES soups(id),
    fish BIGINT NOT NULL REFERENCES fishes(id),
    meat BIGINT NOT NULL REFERENCES meats(id),
    dessert BIGINT NOT NULL REFERENCES desserts(id),
    room_dinis BOOLEAN NOT NULL,
    room_isabel BOOLEAN NOT NULL,
    room_joaoIII BOOLEAN NOT NULL,
    room_leonor BOOLEAN NOT NULL,
    room_espelhos BOOLEAN NOT NULL,
    room_atrium BOOLEAN NOT NULL,
    lago BOOLEAN NOT NULL,
    lago_extras VARCHAR(255) ,
    auditorio BOOLEAN NOT NULL,
    auditorio_extras VARCHAR(255),
    jardim BOOLEAN NOT NULL,
    jardim_extras VARCHAR(255),
    decoration VARCHAR(255)  NOT NULL,
    entertainment VARCHAR(255) NOT NULL,
    extras VARCHAR(255) NOT NULL,
    qp_resp_name  VARCHAR(255)  NOT NULL,
    qp_resp_contact VARCHAR(31) NOT NULL,
    client_resp_name VARCHAR(255)  NOT NULL,
    client_resp_contact VARCHAR(31) NOT NULL,
    client_resp_email VARCHAR(31) NOT NULL,
    current_status  BIGINT NOT NULL REFERENCES statuses(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fire BOOLEAN NOT NULL,
    lake_music BOOLEAN NOT NULL,
    auditorium_music BOOLEAN NOT NULL,
    stage BOOLEAN NOT NULL,
    collision_ids VARCHAR(255),
    deleted BOOLEAN NOT NULL
    );


insert into event_types (option) values ('Casamento');
insert into event_types (option) values ('Baptizado');
insert into event_types (option) values ('Empresa');

insert into statuses (option) values ('Reservado');
insert into statuses (option) values ('Cancelado');
insert into statuses (option) values ('Pago');
insert into statuses (option) values ('Sinalizado');

insert into appetizers (name, price, details) VALUES ('Camarão', 22.55 , 'tostado, cozido a vapor ambiguo');
insert into appetizers (name, price, details) values ('Ameijoa com limao', 22 , 'extras');
insert into appetizers (name, price, details) values ('Sushi', 22.55 , 'tostado,ahahhaahh,ambiguo');

insert into soups (name, price, details) values ('Feijao',22, 'feijoa,couve assim,tomate cortado');
insert into soups (name, price, details) values ('Peixe',25.2, 'nao');
insert into soups (name, price, details) values ('Couve lombarda',22, 'bucha,couve,cortado');

insert into meats (name, price,details) values ('Leitao assado',22,'meat1 + extras, ups1');
insert into meats (name, price,details) values ('Vitela estufada',22,'meat2 + extras, ups2');
insert into meats (name, price,details) values ('Frango no churrasco',22,'meat3 + extras, ups3');

insert into fishes (name, price,details) values ('Espadarte escalado gratinado',22,'extras, goooo');
insert into fishes (name, price,details) values ('Salmao grelhado',22,'fish2 goooo2');
insert into fishes (name, price,details) values ('Atum Brazeado',22,'fish3 goooo2');

insert into desserts (name, price,details) values ('Arroz doce',22,'sobremesa extras');
insert into desserts (name, price,details) values ('Leite creme',22,'aloy');
insert into desserts (name, price,details) values ('Baba de camelo',22,'sdddddddddddddd');




