drop table events;
drop table statuses;
drop table event_types;
drop table appetizers;
drop table meats;
drop table desserts;
drop table soups;
drop table fishes;


CREATE TABLE IF NOT EXISTS statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    option VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS event_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    option VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS appetizers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    details VARCHAR(255),
    photo VARCHAR(255),
    galery VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS soups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    details VARCHAR(255),
    photo VARCHAR(255),
    galery VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS fishes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    details VARCHAR(255),
    photo VARCHAR(255),
    galery VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS meats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    details VARCHAR(255),
    photo VARCHAR(255),
    galery VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS desserts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    details VARCHAR(255),
    photo VARCHAR(255),
    galery VARCHAR(255)
);



CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    num_person SMALLINT NOT NULL,
    num_children SMALLINT NOT NULL,
    num_free_children SMALLINT NOT NULL,
    event_date_start TIMESTAMP ,
    event_date_end TIMESTAMP ,
    event_type BIGINT REFERENCES event_types(id),
    appetizer BIGINT REFERENCES appetizers(id),
    soup BIGINT REFERENCES soups(id),
    fish BIGINT REFERENCES fishes(id),
    meat BIGINT REFERENCES meats(id),
    dessert BIGINT REFERENCES desserts(id),
    room_dinis BOOLEAN,
    room_isabel BOOLEAN,
    room_joaoIII BOOLEAN,
    room_leonor BOOLEAN,
    room_espelhos BOOLEAN,
    room_atrium BOOLEAN,
    lago BOOLEAN,
    lago_extras VARCHAR(255) ,
    auditorio BOOLEAN,
    auditorio_extras VARCHAR(255),
    jardim BOOLEAN,
    jardim_extras VARCHAR(255),
    decoration VARCHAR(255) ,
    entertainment VARCHAR(255),
    extras VARCHAR(255),
    qp_resp_name  VARCHAR(255)  NOT NULL,
    qp_resp_contact VARCHAR(31) NOT NULL,
    client_resp_name VARCHAR(255)  NOT NULL,
    client_resp_contact VARCHAR(31) NOT NULL,
    client_resp_email VARCHAR(31) NOT NULL,
    current_status  BIGINT REFERENCES statuses(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fire BOOLEAN,
    lake_music BOOLEAN,
    auditorium_music BOOLEAN,
    stage BOOLEAN,
    collision_ids VARCHAR(255),
    deleted BOOLEAN
    );


insert into event_types (option) values ('Casamento');
insert into event_types (option) values ('Baptizado');
insert into event_types (option) values ('Empresa');
insert into event_types (option) values ('Bodas');
insert into event_types (option) values ('Militar');
insert into event_types (option) values ('Outros');
insert into event_types (option) values ('Aniversário');

insert into statuses (option) values ('Reservado');
insert into statuses (option) values ('Cancelado');
insert into statuses (option) values ('Pago');
insert into statuses (option) values ('Sinalizado');

insert into appetizers (name, price, details, photo, galery) VALUES ('Camarão', 22.55 , 'tostado, cozido a vapor ambiguo','camarao.jpeg','c1.jpeg, c2.jpeg');
insert into appetizers (name, price, details, photo) values ('Ameijoa com limao', 22 , 'extras','ameijoa.jpeg');
insert into appetizers (name, price, details, photo) values ('Sushi', 22.55 , 'tostado,ahahhaahh,ambiguo','sushi.jpeg');

insert into soups (name, price, details, photo) values ('Feijao',22, 'feijoa,couve assim,tomate cortado','feijao.jpeg');
insert into soups (name, price, details, photo) values ('Peixe',25.2, 'nao','peixe.jpeg');
insert into soups (name, price, details, photo) values ('Couve lombarda',22, 'bucha,couve,cortado','lombarda.jpeg');

insert into meats (name, price,details, photo) values ('Leitao assado',22,'meat1 + extras, ups1','leitao.jpeg');
insert into meats (name, price,details, photo) values ('Vitela estufada',22,'meat2 + extras, ups2','vitela.jpeg');
insert into meats (name, price,details, photo) values ('Frango no churrasco',22,'meat3 + extras, ups3', 'frango.jpeg');

insert into fishes (name, price,details, photo) values ('Espadarte escalado gratinado',22,'extras, goooo','espadarte.jpeg');
insert into fishes (name, price,details, photo) values ('Salmao grelhado',22,'fish2 goooo2','salmao.jpeg');
insert into fishes (name, price,details, photo) values ('Atum Brazeado',22,'fish3 goooo2','atum.jpeg');

insert into desserts (name, price,details, photo) values ('Arroz doce',22,'sobremesa extras','arroz_doce.jpeg');
insert into desserts (name, price,details, photo) values ('Leite creme',22,'aloy','leite_creme.jpeg');
insert into desserts (name, price,details, photo) values ('Baba de camelo',22,'sdddddddddddddd','baba_camelo.jpeg');
